# Generated by Django 4.1.7 on 2023-02-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('supplier_code', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('primary_phone', models.CharField(max_length=15)),
                ('secondary_phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('additional_email', models.EmailField(blank=True, max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('additional_address', models.TextField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Supplier',
                'db_table': 'Supplier',
            },
        ),
    ]
