# Generated by Django 4.1.7 on 2023-02-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='primary_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='additional_address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='additional_email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='description',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='secondary_phone',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_code',
        ),
        migrations.AddField(
            model_name='supplier',
            name='tin_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='vrn_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
