# Generated by Django 4.1.7 on 2023-02-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='nationality',
            field=models.CharField(blank=True, default='Tanzania', max_length=50, null=True, verbose_name='Nationality'),
        ),
    ]
