# Generated by Django 4.1.7 on 2023-02-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expesne', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.AddField(
            model_name='expense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
