# Generated by Django 4.1.7 on 2023-02-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('tin_number', models.CharField(blank=True, max_length=100)),
                ('vrn_number', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('address', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Customer',
                'db_table': 'Customer',
            },
        ),
    ]
