# Generated by Django 4.1.7 on 2023-02-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tax_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
