# Generated by Django 4.1.7 on 2023-02-20 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, unique=True)),
                ('value', models.FloatField(default=0.0)),
                ('delivery_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_transfer', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=0, help_text='Quantity received')),
                ('buying_price', models.FloatField(default=1.0)),
                ('retail_price', models.FloatField(default=0.0)),
                ('wholesale_price', models.FloatField(default=0.0)),
                ('current_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliveries.delivery')),
                ('home_branch', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_location', to='branches.branch')),
            ],
        ),
    ]
