# Generated by Django 4.1.7 on 2023-02-21 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={},
        ),
    ]
