# Generated by Django 4.1.7 on 2023-02-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('SERVICE', 'Service'), ('COMSUMABLE', 'Consumable')], default=2222, max_length=100, verbose_name='product service'),
            preserve_default=False,
        ),
    ]
